services:
  postgres:
    image: 'postgres:16.4-alpine3.20'
    container_name: postgrescontainerlff
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: momo69
      POSTGRES_USER: mohamed
      POSTGRES_DB: lff
    networks:
      - lafacturefacile-network
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmincontainerlff
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: PASSWORD
        PGADMIN_LISTEN_PORT: 8001
    ports:
      - 8001:8001
    depends_on:
      - postgres 
    networks:
      - lafacturefacile-network
    command: sh -c "dockerize -wait tcp://postgres:5433 -timeout 300s -wait-retry-interval 30s /entrypoint.sh"
networks:
  lafacturefacile-network:
    name: lafacturefacile-network