services:
  # postgres:
  #   image: 'postgres:16.4-alpine3.20'
  #   container_name: postgrescontainerlff
  #   restart: always
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_PASSWORD: momo69
  #     POSTGRES_USER: mohamed
  #     POSTGRES_DB: lff
  #   networks:
  #     - lafacturefacile-network
  lafacturefacile:
    image: lafacturefacile:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - "8081:8081"
    # depends_on:
    #   - postgres
    environment:
      # SPRING_PROFILES_ACTIVE: prod  # Utiliser les profils Spring
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lff
      SPRING_DATASOURCE_USERNAME: mohamed
      SPRING_DATASOURCE_PASSWORD: momo69
    networks:
      - lafacturefacile-network
    command: sh -c "dockerize -wait tcp://postgres:5433 -timeout 300s -wait-retry-interval 30s /entrypoint.sh"
  # pgadmin4:
  #   image: dpage/pgadmin4
  #   container_name: pgadmincontainerlff
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #       PGADMIN_DEFAULT_PASSWORD: PASSWORD
  #       PGADMIN_LISTEN_PORT: 8001
  #   ports:
  #     - 8001:8001
  #   # depends_on:
  #   #   - postgres 
  #   networks:
  #     - lafacturefacile-network
  #   command: sh -c "dockerize -wait tcp://postgres:5433 -timeout 300s -wait-retry-interval 30s /entrypoint.sh"
networks:
  lafacturefacile-network:
    # external: true
    name: lafacturefacile-network