services:
  backend:
    image: mohamedd69/lafacturefacile
    container_name: lafacturefacile-backend
    restart: always
    environment:
      - spring.datasource.url=${DB_HOST}
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}
      - JAVA_TOOL_OPTIONS=-Xss200k
      - file.upload-dir=${UPLOAD_DIR}
    volumes:
      - /var/private_data/pdfs:/app/pdfs
      - /var/run/docker.sock:/var/run/docker.sock
    user: "lffappuser"
    networks:
      - lafacturefacile-network
networks:
  lafacturefacile-network:
    external: true
    name: lafacturefacile-network