# Utiliser l'image Maven avec JDK pour le développement
FROM maven:3.9.9-eclipse-temurin-17-alpine AS dev

# Créer un utilisateur et un groupe
RUN groupadd -r lffusergroup && useradd -r -g lffusergroup -m lffappuser

# Créer le répertoire où les PDF seront enregistrés
RUN mkdir -p /app/pdfs

# Donner les permissions nécessaires sur le répertoire
RUN chown -R lffappuser:lffusergroup /app/pdfs
RUN chmod -R 750 /app/pdfs

# Passer à l'utilisateur myuser
USER lffappuser

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement le pom.xml pour installer les dépendances
COPY pom.xml ./
RUN mvn dependency:go-offline -B && mvn clean

# Copier les sources (seront remplacées par le volume dans Docker Compose)
COPY src ./src

# Exposer le port sur lequel l'application va tourner
EXPOSE 8080

# Commande pour lancer Spring Boot en mode développement
CMD ["mvn", "spring-boot:run"]
