CREATE TABLE IF NOT EXISTS "invoice"(
    id serial primary key,
    invoice_number varchar(50),
    tmp_invoice_number varchar(50) not null,
    seller_name varchar(100) not null,
    seller_email varchar(200) not null,
    seller_address varchar(200) not null,
    seller_phone varchar(20) not null,
    seller_siret varchar(30) not null,
    customer_name varchar(40) not null,
    customer_email varchar(200) not null,
    customer_address varchar(200) not null,
    customer_phone varchar(20) not null,
    creation_date TIMESTAMPTZ not null,
    expiration_date TIMESTAMPTZ not null,
    status varchar(50) not null,
    amount_ht NUMERIC(15,2) not null,
    amount_ttc NUMERIC(15,2) not null,
    user_id integer not null,
    file_id integer not null,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user_entity(id) ON DELETE CASCADE,
    CONSTRAINT fk_file FOREIGN KEY (file_id) REFERENCES file_info(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "items" (
    id SERIAL PRIMARY KEY,
    product_name VARCHAR(200) NOT NULL,
    price_ht NUMERIC(15,2) NOT NULL,
    price_ttc NUMERIC(15,2) NOT NULL,
    tax NUMERIC(5,2) NOT NULL,
    quantity INT NOT NULL,
    total_ht NUMERIC(15,2) NOT NULL,
    total_ttc NUMERIC(15,2) NOT NULL,
    description TEXT,
    invoice_id INT NOT NULL,
    CONSTRAINT fk_invoice FOREIGN KEY (invoice_id) REFERENCES invoice(id) ON DELETE CASCADE
);